"""
Code Mode Output — standard JSON envelope and formatting helpers.

Every scaffolded Code Mode integration emits the same envelope shape:
  { success, mode, result, console, audit, meta, error }

Generated by codemode-scaffold. Template version: 1.0.0
"""

from __future__ import annotations

import json


# --- Truncation ---

DEFAULT_RESULT_MAX_BYTES = 50_000
DEFAULT_CONSOLE_MAX_BYTES = 10_000


def truncate_json_payload(payload, max_bytes: int = DEFAULT_RESULT_MAX_BYTES) -> tuple[object, bool]:
    """Truncate a JSON-serializable payload if it exceeds max_bytes.

    Returns (payload_or_truncated, was_truncated).
    """
    try:
        raw = json.dumps(payload, ensure_ascii=False, default=str)
    except TypeError:
        raw = json.dumps(str(payload), ensure_ascii=False)

    raw_bytes = raw.encode("utf-8")
    if len(raw_bytes) <= max_bytes:
        return payload, False

    preview = raw_bytes[:max_bytes].decode("utf-8", errors="ignore")
    return (
        {
            "_truncated": True,
            "preview": preview,
            "original_size_bytes": len(raw_bytes),
        },
        True,
    )


def truncate_console(
    console_entries: list,
    max_bytes: int = DEFAULT_CONSOLE_MAX_BYTES,
) -> tuple[list, bool]:
    """Truncate console entries if total byte size exceeds max_bytes."""
    if not isinstance(console_entries, list):
        return [], False

    kept: list[str] = []
    used = 0
    truncated = False
    for entry in console_entries:
        line = str(entry)
        line_bytes = len(line.encode("utf-8"))
        if used + line_bytes > max_bytes:
            truncated = True
            break
        kept.append(line)
        used += line_bytes

    return kept, truncated


# --- Envelope construction ---

def build_envelope(
    *,
    success: bool,
    mode: str,
    result: object = None,
    console: list | None = None,
    audit: list | None = None,
    duration_ms: int = 0,
    request_count: int = 0,
    max_requests: int = 0,
    timeout_seconds: int = 0,
    truncated: bool = False,
    spec_sha256: str | None = None,
    error: dict | None = None,
    result_max_bytes: int = DEFAULT_RESULT_MAX_BYTES,
    console_max_bytes: int = DEFAULT_CONSOLE_MAX_BYTES,
) -> dict:
    """Build a standard Code Mode output envelope.

    Applies truncation to result and console automatically.
    """
    result_truncated = False
    console_truncated = False

    if success and result is not None:
        result, result_truncated = truncate_json_payload(result, result_max_bytes)

    console_out, console_truncated = truncate_console(
        console or [], console_max_bytes
    )

    return {
        "success": success,
        "mode": mode,
        "result": result if success else None,
        "console": console_out,
        "audit": audit or [],
        "meta": {
            "duration_ms": duration_ms,
            "request_count": request_count,
            "max_requests": max_requests,
            "timeout_seconds": timeout_seconds,
            "truncated": truncated or result_truncated or console_truncated,
            "spec_sha256": spec_sha256,
        },
        "error": error,
    }


# --- Human-readable formatting ---

def format_envelope_human(envelope: dict) -> str:
    """Format a Code Mode envelope for human-readable terminal output."""
    lines: list[str] = []

    if envelope.get("success"):
        lines.append(f"✅ Code mode {envelope.get('mode')} completed")
    else:
        lines.append(f"❌ Code mode {envelope.get('mode')} failed")

    error_payload = envelope.get("error")
    if error_payload:
        lines.append(f"Error [{error_payload.get('type')}]: {error_payload.get('message')}")

    result_payload = envelope.get("result")
    if result_payload is not None:
        lines.append("\nResult:")
        lines.append(json.dumps(result_payload, indent=2, ensure_ascii=False))

    console_output = envelope.get("console") or []
    if console_output:
        lines.append("\nConsole:")
        for entry in console_output:
            lines.append(f"  • {entry}")

    audit = envelope.get("audit") or []
    if audit:
        lines.append("\nAudit:")
        for entry in audit:
            # Support both REST (method/path/status) and MCP (tool/ok) audit entries
            if "method" in entry:
                method = entry.get("method", "?")
                path = entry.get("path", "?")
                status = entry.get("status", "?")
                duration = entry.get("duration_ms", 0)
                lines.append(f"  [{entry.get('seq', '?')}] {method} {path} → {status} ({duration}ms)")
            elif "tool" in entry:
                tool = entry.get("tool", "?")
                ok = "✓" if entry.get("ok") else "✗"
                duration = entry.get("duration_ms", 0)
                lines.append(f"  [{entry.get('seq', '?')}] {tool} → {ok} ({duration}ms)")

    meta = envelope.get("meta") or {}
    if meta:
        lines.append(f"\nMeta: {meta.get('request_count', 0)}/{meta.get('max_requests', 0)} requests, "
                      f"{meta.get('duration_ms', 0)}ms total"
                      + (", truncated" if meta.get("truncated") else ""))

    return "\n".join(lines)
