#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""
Code Mode MCP Tool Index Builder — extract and cache tool metadata for search mode.

Reads tool definitions from an MCP server and builds a compact search index
with tool name, description, input schema, and classification hints.

Generated by codemode-scaffold. Template version: 1.0.0

Customization points:
  - SERVER_SCRIPT: path to the MCP server script
  - CACHE_SUBDIR: subdirectory name under ~/.cache/shuvbot/
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path


# --- Customization points ---
SERVER_SCRIPT = "make_api_server.py"
CACHE_SUBDIR = "make-api"
GENERATOR_VERSION = "v1"
DEFAULT_MAX_AGE_HOURS = 24


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def default_cache_dir() -> Path:
    xdg_cache = os.environ.get("XDG_CACHE_HOME")
    base = Path(xdg_cache).expanduser() if xdg_cache else (Path.home() / ".cache")
    return base / "shuvbot" / CACHE_SUBDIR


def write_json_atomic(path: Path, payload: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    tmp_path.replace(path)


def extract_tools_from_registry(tools: list[dict]) -> list[dict]:
    """Extract searchable metadata from MCP tool descriptors."""
    entries = []
    for tool in tools:
        if not isinstance(tool, dict):
            continue

        name = tool.get("name", "")
        if not name:
            continue

        entry = {
            "name": name,
            "description": tool.get("description", ""),
            "inputSchema": tool.get("inputSchema", {}),
            "tags": [],
        }

        # Extract classification hints from annotations
        annotations = tool.get("annotations", {})
        if isinstance(annotations, dict):
            if annotations.get("readOnlyHint"):
                entry["readOnlyHint"] = True
            if annotations.get("destructiveHint"):
                entry["writeHint"] = True

        entries.append(entry)

    entries.sort(key=lambda e: e.get("name", ""))
    return entries


def build_index(tools: list[dict], source: str) -> dict:
    """Build a search index from tool entries."""
    raw = json.dumps(tools, sort_keys=True).encode("utf-8")
    sha256 = hashlib.sha256(raw).hexdigest()

    return {
        "schema_version": 1,
        "generated_at": utc_now_iso(),
        "source": source,
        "tools_sha256": sha256,
        "tools": extract_tools_from_registry(tools),
    }


def parse_iso8601(value: str | None) -> datetime | None:
    if not value or not isinstance(value, str):
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def ensure_index(
    cache_dir: Path,
    tools: list[dict],
    source: str,
    refresh: bool,
    max_age_hours: int,
) -> tuple[dict, bool]:
    """Return (index, did_refresh). Uses cache if fresh enough."""
    index_path = cache_dir / "tools.index.v1.json"

    if not refresh and index_path.exists():
        try:
            existing = json.loads(index_path.read_text(encoding="utf-8"))
            generated_at = parse_iso8601(existing.get("generated_at"))
            if generated_at:
                is_stale = (datetime.now(timezone.utc) - generated_at) > timedelta(hours=max_age_hours)
                if not is_stale:
                    return existing, False
        except json.JSONDecodeError:
            pass

    index = build_index(tools, source)
    write_json_atomic(index_path, index)
    return index, True


def main():
    parser = argparse.ArgumentParser(description="Build MCP tool search index")
    parser.add_argument("--tools-file", type=str, help="JSON file with tool definitions")
    parser.add_argument("--refresh", action="store_true", help="Force rebuild")
    parser.add_argument("--cache-dir", type=str, help="Override cache directory")
    parser.add_argument("--json", action="store_true", help="Print JSON summary")
    args = parser.parse_args()

    cache_dir = Path(args.cache_dir).expanduser() if args.cache_dir else default_cache_dir()

    tools: list[dict] = []
    source = "manual"

    if args.tools_file:
        tools_path = Path(args.tools_file).expanduser()
        if tools_path.exists():
            tools = json.loads(tools_path.read_text(encoding="utf-8"))
            source = str(tools_path)

    index, did_refresh = ensure_index(
        cache_dir=cache_dir,
        tools=tools,
        source=source,
        refresh=args.refresh,
        max_age_hours=DEFAULT_MAX_AGE_HOURS,
    )

    summary = {
        "refreshed": did_refresh,
        "cache_dir": str(cache_dir),
        "tool_count": len(index.get("tools", [])),
        "tools_sha256": index.get("tools_sha256"),
        "generated_at": index.get("generated_at"),
    }

    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        status = "refreshed" if did_refresh else "cached"
        print(f"[{status}] MCP tool index ready")
        print(f"cache_dir: {summary['cache_dir']}")
        print(f"tools: {summary['tool_count']}")
        print(f"sha256: {summary['tools_sha256']}")


if __name__ == "__main__":
    main()
