"""
Code Mode MCP Adapter — handles tool-call execution for MCP-based skills.

Provides the execute_fn callback for the host broker. Handles:
  - Tool resolution and invocation
  - Response normalization
  - Tool registry access

Generated by codemode-scaffold. Template version: 1.0.0

Customization points:
  - load_tools_registry(): load available tools from MCP server
  - invoke_tool(): call a specific tool with arguments
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any


# --- Customization points ---

def load_tools_registry(server_script: str | None = None) -> list[dict]:
    """Load the tool registry from the MCP server.

    Override this to match your MCP server's tool discovery mechanism.
    Returns a list of tool descriptors: [{"name": ..., "description": ..., "inputSchema": ...}]
    """
    # Default: try to read tools from the server via stdio
    if server_script is None:
        server_script = str(Path(__file__).parent / "make_api_server.py")

    # Placeholder — in practice, you'd start the MCP server and list_tools
    return []


def invoke_tool(tool_name: str, args: dict, server_script: str | None = None) -> tuple[bool, Any]:
    """Invoke an MCP tool by name with the given arguments.

    Override this to match your MCP server's invocation mechanism.

    Returns (ok: bool, result: Any).
    For sidecar mode, this typically calls the MCP server via mcporter or subprocess.
    """
    if server_script is None:
        server_script = str(Path(__file__).parent / "make_api_server.py")

    # Default implementation: use mcporter CLI
    try:
        result = subprocess.run(
            [
                sys.executable, "-m", "mcporter",
                "call", f"{{make-api}}.{tool_name}",
                "--args", json.dumps(args),
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )

        if result.returncode == 0:
            try:
                parsed = json.loads(result.stdout)
                return True, parsed
            except json.JSONDecodeError:
                return True, {"raw": result.stdout.strip()}
        else:
            return False, {"error": result.stderr.strip() or "Tool invocation failed"}

    except subprocess.TimeoutExpired:
        return False, {"error": f"Tool '{tool_name}' timed out"}
    except Exception as exc:
        return False, {"error": str(exc)}


# --- MCP adapter implementation ---

class McpAdapter:
    """MCP adapter for Code Mode execute_fn."""

    def __init__(
        self,
        server_script: str | None = None,
        tools_registry: list[dict] | None = None,
    ):
        self.server_script = server_script
        self.tools_registry = tools_registry or load_tools_registry(server_script)
        self._tools_by_name = {t["name"]: t for t in self.tools_registry}

    def get_tool(self, name: str) -> dict | None:
        """Look up a tool by name."""
        return self._tools_by_name.get(name)

    def list_tools(self) -> list[dict]:
        """Return all available tools."""
        return self.tools_registry

    def execute(self, normalized_request: dict) -> tuple[bool, Any]:
        """Execute a normalized MCP tool call. Returns (ok, result).

        This is the execute_fn passed to run_codemode().
        """
        tool_name = normalized_request["tool"]
        args = normalized_request.get("args", {})

        tool = self.get_tool(tool_name)
        if tool is None:
            return False, {"error": f"Tool '{tool_name}' not found in registry"}

        return invoke_tool(tool_name, args, self.server_script)
