"""
Code Mode Policy — safety gates and validation for host-mediated operations.

Enforces read-only defaults, write gates, request/call caps, and path/tool validation.
All policy decisions are made host-side; the sandboxed runner has no direct access.

Generated by codemode-scaffold. Template version: 1.0.0
"""

from __future__ import annotations

from urllib.parse import urlsplit


# --- Error taxonomy ---

class CodemodeError(Exception):
    """Base error for all Code Mode failures."""
    error_type = "RuntimeError"

    def __init__(self, message: str, details: dict | None = None):
        super().__init__(message)
        self.message = message
        self.details = details or {}

    def to_payload(self) -> dict:
        return {
            "type": self.error_type,
            "message": self.message,
            "details": self.details,
        }


class ValidationError(CodemodeError):
    """Input validation failure (bad code, missing args, malformed request)."""
    error_type = "ValidationError"


class PolicyError(CodemodeError):
    """Policy violation (write without permission, method not allowed, cap exceeded)."""
    error_type = "PolicyError"


class RuntimeExecutionError(CodemodeError):
    """Runtime failure (runner crash, node not found, unexpected error)."""
    error_type = "RuntimeError"


class TimeoutExecutionError(CodemodeError):
    """Execution exceeded timeout."""
    error_type = "TimeoutError"


# --- REST policy ---

READ_ONLY_METHODS = frozenset({"GET", "HEAD"})
WRITE_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})
ALLOWED_METHODS = READ_ONLY_METHODS | WRITE_METHODS


def validate_relative_api_path(path: str) -> str:
    """Validate and normalize a relative API path. Rejects absolute URLs."""
    if not isinstance(path, str) or not path.strip():
        raise ValidationError("Request path must be a non-empty string")
    if not path.startswith("/"):
        raise ValidationError("Request path must start with '/'")

    parsed = urlsplit(path)
    if parsed.scheme or parsed.netloc:
        raise ValidationError("Request path must be relative and must not include scheme/host")

    normalized = parsed.path
    if parsed.query:
        normalized = f"{normalized}?{parsed.query}"
    return normalized


def normalize_rest_request(
    request_payload: dict,
    allow_write: bool,
    assume_yes: bool,
) -> dict:
    """Validate and normalize an RPC REST request. Enforces method + write gates."""
    if not isinstance(request_payload, dict):
        raise ValidationError("request payload must be an object")

    method = str(request_payload.get("method", "GET")).upper()
    if method not in ALLOWED_METHODS:
        raise PolicyError(
            f"Method '{method}' is not allowed",
            {"allowed_methods": sorted(ALLOWED_METHODS)},
        )

    if method in WRITE_METHODS and not (allow_write and assume_yes):
        raise PolicyError("Write methods require both --allow-write and --yes")

    path = validate_relative_api_path(request_payload.get("path", ""))

    query = request_payload.get("query")
    if query is not None and not isinstance(query, dict):
        raise ValidationError("query must be an object when provided")

    headers = request_payload.get("headers")
    if headers is not None and not isinstance(headers, dict):
        raise ValidationError("headers must be an object when provided")

    return {
        "method": method,
        "path": path,
        "query": query,
        "body": request_payload.get("body"),
        "headers": headers,
    }


# --- MCP policy ---

def classify_mcp_tool(
    tool_name: str,
    policy_config: dict,
) -> str:
    """Classify an MCP tool as 'read' or 'write' based on policy config.

    Returns 'read', 'write', or 'unknown'.
    """
    read_tools = set(policy_config.get("read_tools", []))
    write_tools = set(policy_config.get("write_tools", []))

    if tool_name in read_tools:
        return "read"
    if tool_name in write_tools:
        return "write"

    # Pattern rules (prefix/suffix)
    for rule in policy_config.get("pattern_rules", []):
        pattern_type = rule.get("type", "prefix")
        pattern = rule.get("pattern", "")
        classification = rule.get("classification", "unknown")

        if pattern_type == "prefix" and tool_name.startswith(pattern):
            return classification
        if pattern_type == "suffix" and tool_name.endswith(pattern):
            return classification

    return "unknown"


def normalize_mcp_request(
    request_payload: dict,
    allow_write: bool,
    assume_yes: bool,
    policy_config: dict,
    allow_unknown_tools: bool = False,
) -> dict:
    """Validate and normalize an MCP tool call request. Enforces tool policy."""
    if not isinstance(request_payload, dict):
        raise ValidationError("callTool payload must be an object")

    tool_name = request_payload.get("tool")
    if not isinstance(tool_name, str) or not tool_name.strip():
        raise ValidationError("Tool name must be a non-empty string")

    args = request_payload.get("args")
    if args is not None and not isinstance(args, dict):
        raise ValidationError("Tool args must be an object when provided")

    classification = classify_mcp_tool(tool_name, policy_config)

    if classification == "write" and not (allow_write and assume_yes):
        raise PolicyError(
            f"Tool '{tool_name}' is classified as write — requires --allow-write and --yes",
            {"tool": tool_name, "classification": classification},
        )

    if classification == "unknown" and not allow_unknown_tools:
        raise PolicyError(
            f"Tool '{tool_name}' is not classified in policy config — denied by default",
            {"tool": tool_name, "hint": "Add to read_tools/write_tools or use --allow-unknown-tools"},
        )

    return {
        "tool": tool_name.strip(),
        "args": args or {},
        "classification": classification,
    }


# --- Shared policy helpers ---

def validate_timeout(timeout_seconds: int) -> None:
    """Ensure timeout is positive."""
    if timeout_seconds <= 0:
        raise ValidationError("--timeout must be greater than 0")


def validate_max_calls(max_calls: int) -> None:
    """Ensure max calls/requests is non-negative."""
    if max_calls < 0:
        raise ValidationError("--max-requests/--max-calls must be >= 0")


def check_call_cap(current_count: int, max_calls: int) -> None:
    """Raise PolicyError if call count exceeds cap."""
    if current_count > max_calls:
        raise PolicyError(
            f"Max request/call count exceeded ({max_calls})",
            {"max_calls": max_calls, "current": current_count},
        )
