#!/usr/bin/env node
/**
 * Code Mode Runner — Sandboxed JavaScript execution engine
 *
 * Executes user-provided JavaScript in a Node.js vm sandbox.
 * Communicates with the Python host broker via JSON-line protocol on stdin/stdout.
 *
 * Protocol:
 *   Host → Runner: { type: "init", payload: { mode, code, spec?, config? } }
 *   Runner → Host: { type: "rpc_request", id, request }
 *   Host → Runner: { type: "rpc_response", id, ok, result?, error? }
 *   Runner → Host: { type: "result", result, console, truncated }
 *   Runner → Host: { type: "error", error, console, truncated }
 *
 * Generated by codemode-scaffold. Template version: 1.0.0
 */
import readline from 'node:readline';
import vm from 'node:vm';

const rl = readline.createInterface({
  input: process.stdin,
  crlfDelay: Infinity,
});

let initialized = false;
let config = {};
let rpcSeq = 0;
const pendingRpc = new Map();

let consoleEntries = [];
let consoleBytes = 0;
let consoleTruncated = false;
let resultTruncated = false;
let maxConsoleBytes = 10_000;
let maxResultBytes = 50_000;
let completed = false;

function send(message) {
  process.stdout.write(`${JSON.stringify(message)}\n`);
}

function toDisplay(value) {
  if (typeof value === 'string') return value;
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

function appendConsole(level, args) {
  if (consoleTruncated) return;
  const line = `[${level}] ${args.map(toDisplay).join(' ')}`;
  const lineBytes = Buffer.byteLength(line, 'utf8');
  if (consoleBytes + lineBytes > maxConsoleBytes) {
    consoleTruncated = true;
    return;
  }
  consoleEntries.push(line);
  consoleBytes += lineBytes;
}

function truncateResultValue(result) {
  let encoded;
  try {
    encoded = JSON.stringify(result);
  } catch {
    const err = new Error('Returned value is not JSON-serializable');
    err.name = 'ValidationError';
    throw err;
  }

  const size = Buffer.byteLength(encoded, 'utf8');
  if (size <= maxResultBytes) {
    return result;
  }

  const preview = Buffer.from(encoded, 'utf8').subarray(0, maxResultBytes).toString('utf8');
  resultTruncated = true;
  return {
    _truncated: true,
    preview,
    original_size_bytes: size,
  };
}

function normalizeError(error) {
  const allowed = new Set(['ValidationError', 'RuntimeError', 'TimeoutError', 'PolicyError']);
  const type = allowed.has(error?.name) ? error.name : 'RuntimeError';
  return {
    type,
    message: error?.message || 'Code mode execution failed',
    details: typeof error?.details === 'object' && error.details ? error.details : {},
  };
}

function deepFreeze(input) {
  if (!input || typeof input !== 'object') {
    return input;
  }
  Object.freeze(input);
  for (const key of Object.keys(input)) {
    const value = input[key];
    if (value && typeof value === 'object' && !Object.isFrozen(value)) {
      deepFreeze(value);
    }
  }
  return input;
}

// Generic RPC call — adapter name is injected by host config
async function rpcCall(requestPayload) {
  return new Promise((resolve, reject) => {
    const id = ++rpcSeq;
    pendingRpc.set(id, { resolve, reject });
    send({ type: 'rpc_request', id, request: requestPayload });
  });
}

function createSandbox() {
  const safeConsole = Object.freeze({
    log: (...args) => appendConsole('log', args),
    info: (...args) => appendConsole('info', args),
    warn: (...args) => appendConsole('warn', args),
    error: (...args) => appendConsole('error', args),
    debug: (...args) => appendConsole('debug', args),
  });

  const sandbox = {
    console: safeConsole,
  };

  // Search mode: expose frozen spec/index
  if (config.mode === 'search') {
    sandbox.spec = deepFreeze(config.spec || { operations: [] });
  }

  // Execute mode: expose adapter interface
  if (config.mode === 'execute') {
    const adapterName = config.adapterName || 'codemode';

    if (config.adapterType === 'rest') {
      // REST adapter: codemode.request({ method, path, query, body, headers })
      sandbox[adapterName] = Object.freeze({
        request: (payload) => rpcCall({ type: 'rest_request', ...payload }),
      });
    } else if (config.adapterType === 'mcp') {
      // MCP adapter: codemode.callTool({ tool, args })
      sandbox[adapterName] = Object.freeze({
        callTool: (payload) => rpcCall({ type: 'mcp_call_tool', ...payload }),
      });
    } else {
      // Generic fallback — expose both
      sandbox[adapterName] = Object.freeze({
        request: (payload) => rpcCall({ type: 'rest_request', ...payload }),
        callTool: (payload) => rpcCall({ type: 'mcp_call_tool', ...payload }),
      });
    }
  }

  return sandbox;
}

async function runUserCode() {
  const mode = config.mode;
  if (mode !== 'search' && mode !== 'execute') {
    const err = new Error(`Unsupported mode: ${mode}`);
    err.name = 'ValidationError';
    throw err;
  }

  if (typeof config.code !== 'string' || config.code.trim().length === 0) {
    const err = new Error('Missing JavaScript source. Provide --code or --code-file.');
    err.name = 'ValidationError';
    throw err;
  }

  const sandbox = createSandbox();
  const context = vm.createContext(sandbox, {
    name: 'codemode',
    codeGeneration: { strings: false, wasm: false },
  });

  let fn;
  try {
    const compiled = new vm.Script(`(${config.code})`, {
      filename: 'codemode-user.js',
      displayErrors: true,
    });
    fn = compiled.runInContext(context, { timeout: 1_000 });
  } catch (error) {
    const err = new Error(`Failed to compile code: ${error.message}`);
    err.name = 'ValidationError';
    throw err;
  }

  if (typeof fn !== 'function') {
    const err = new Error('Code must evaluate to a function (expected async () => { ... })');
    err.name = 'ValidationError';
    throw err;
  }

  const result = await Promise.resolve(fn());
  return truncateResultValue(result);
}

async function startExecution() {
  try {
    const result = await runUserCode();
    completed = true;
    send({
      type: 'result',
      result,
      console: consoleEntries,
      truncated: consoleTruncated || resultTruncated,
    });
    process.exit(0);
  } catch (error) {
    completed = true;
    send({
      type: 'error',
      error: normalizeError(error),
      console: consoleEntries,
      truncated: consoleTruncated || resultTruncated,
    });
    process.exit(1);
  }
}

rl.on('line', (line) => {
  if (!line || line.trim().length === 0) {
    return;
  }

  let message;
  try {
    message = JSON.parse(line);
  } catch {
    return;
  }

  if (!initialized) {
    if (message.type !== 'init' || typeof message.payload !== 'object' || !message.payload) {
      const err = new Error('First message must be an init payload');
      err.name = 'ValidationError';
      send({ type: 'error', error: normalizeError(err), console: [], truncated: false });
      process.exit(1);
      return;
    }

    initialized = true;
    config = message.payload;

    if (Number.isFinite(config.maxConsoleBytes) && config.maxConsoleBytes > 0) {
      maxConsoleBytes = Math.floor(config.maxConsoleBytes);
    }
    if (Number.isFinite(config.maxResultBytes) && config.maxResultBytes > 0) {
      maxResultBytes = Math.floor(config.maxResultBytes);
    }

    void startExecution();
    return;
  }

  if (message.type === 'rpc_response') {
    const id = message.id;
    const pending = pendingRpc.get(id);
    if (!pending) {
      return;
    }

    pendingRpc.delete(id);
    if (message.ok) {
      pending.resolve(message.result);
      return;
    }

    const details = message.error && typeof message.error === 'object' ? message.error : {};
    const err = new Error(details.message || 'RPC request failed');
    err.name = details.type || 'RuntimeError';
    err.details = details.details || {};
    pending.reject(err);
  }
});

rl.on('close', () => {
  if (!completed) {
    const err = new Error('Runner stdin closed before completion');
    err.name = 'RuntimeError';
    send({ type: 'error', error: normalizeError(err), console: consoleEntries, truncated: consoleTruncated || resultTruncated });
    process.exit(1);
  }
});
