"""
Code Mode Host Broker — orchestrates sandboxed execution via Node runner subprocess.

The host broker:
  1. Spawns the Node runner with an init payload
  2. Mediates all RPC requests (REST API calls or MCP tool calls)
  3. Enforces policy gates on every mediated operation
  4. Collects audit records and console output
  5. Returns a standard JSON envelope

Generated by codemode-scaffold. Template version: 1.0.0
"""

from __future__ import annotations

import json
import os
import select
import shutil
import subprocess
import time
from pathlib import Path
from typing import Callable

from codemode_policy import (
    CodemodeError,
    PolicyError,
    RuntimeExecutionError,
    TimeoutExecutionError,
    ValidationError,
    check_call_cap,
    normalize_mcp_request,
    normalize_rest_request,
    validate_max_calls,
    validate_timeout,
)
from codemode_output import (
    DEFAULT_CONSOLE_MAX_BYTES,
    DEFAULT_RESULT_MAX_BYTES,
    build_envelope,
    truncate_console,
    truncate_json_payload,
)


def read_code_source(code: str | None, code_file: str | None) -> str:
    """Read user code from --code string or --code-file path. Exactly one must be provided."""
    if bool(code) == bool(code_file):
        raise ValidationError("Provide exactly one of --code or --code-file")

    if code_file:
        code_path = Path(code_file).expanduser()
        if not code_path.exists() or not code_path.is_file():
            raise ValidationError(f"Code file not found: {code_file}")
        try:
            return code_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ValidationError(f"Failed to read code file: {code_file}", {"error": str(exc)})

    return str(code)


def _runner_script_path(scripts_dir: Path | None = None) -> Path:
    """Locate the codemode-runner.mjs script."""
    if scripts_dir:
        return scripts_dir / "codemode-runner.mjs"
    return Path(__file__).with_name("codemode-runner.mjs")


def _runner_env() -> dict:
    """Build a minimal, safe environment for the Node runner subprocess."""
    safe_env = {
        "PATH": os.environ.get("PATH", ""),
        "NODE_NO_WARNINGS": "1",
    }
    for key in ("HOME", "TMPDIR", "TMP", "TEMP", "SYSTEMROOT", "WINDIR"):
        if key in os.environ:
            safe_env[key] = os.environ[key]
    return safe_env


def _normalize_runner_error(error_payload) -> dict:
    """Normalize an error payload from the runner into standard shape."""
    if isinstance(error_payload, dict):
        return {
            "type": error_payload.get("type") or "RuntimeError",
            "message": error_payload.get("message") or "Code mode execution failed",
            "details": error_payload.get("details") or {},
        }
    return {
        "type": "RuntimeError",
        "message": str(error_payload) if error_payload else "Code mode execution failed",
        "details": {},
    }


def run_codemode(
    *,
    mode: str,
    code: str,
    adapter_type: str,
    adapter_name: str = "codemode",
    timeout_seconds: int = 30,
    max_requests: int = 20,
    allow_write: bool = False,
    assume_yes: bool = False,
    spec_payload: dict | None = None,
    spec_sha256: str | None = None,
    execute_fn: Callable | None = None,
    policy_config: dict | None = None,
    allow_unknown_tools: bool = False,
    scripts_dir: Path | None = None,
    result_max_bytes: int = DEFAULT_RESULT_MAX_BYTES,
    console_max_bytes: int = DEFAULT_CONSOLE_MAX_BYTES,
) -> dict:
    """Run Code Mode: spawn runner, mediate RPC, return envelope.

    Args:
        mode: 'search' or 'execute'
        code: JavaScript source code
        adapter_type: 'rest' or 'mcp'
        adapter_name: JS object name exposed in sandbox (e.g., 'cloudflare', 'codemode')
        timeout_seconds: max execution time
        max_requests: max RPC calls allowed
        allow_write: whether write operations are permitted
        assume_yes: whether write confirmation is assumed
        spec_payload: search index payload for search mode
        spec_sha256: hash of the spec for audit
        execute_fn: callback(normalized_request) -> (status_code_or_ok, response) for RPC
        policy_config: MCP policy config for tool classification
        allow_unknown_tools: allow unclassified MCP tools
        scripts_dir: override directory to find codemode-runner.mjs
        result_max_bytes: max result payload size
        console_max_bytes: max console output size
    """
    validate_timeout(timeout_seconds)
    validate_max_calls(max_requests)

    runner_path = _runner_script_path(scripts_dir)
    if not runner_path.exists():
        raise RuntimeExecutionError("Code mode runner not found", {"path": str(runner_path)})

    node_bin = shutil.which("node")
    if not node_bin:
        raise RuntimeExecutionError("node binary not found in PATH")

    started = time.monotonic()

    proc = subprocess.Popen(
        [node_bin, str(runner_path)],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
        env=_runner_env(),
    )

    init_message = {
        "type": "init",
        "payload": {
            "mode": mode,
            "code": code,
            "adapterType": adapter_type,
            "adapterName": adapter_name,
            "spec": spec_payload,
            "maxConsoleBytes": console_max_bytes,
            "maxResultBytes": result_max_bytes,
        },
    }

    if proc.stdin is None or proc.stdout is None:
        raise RuntimeExecutionError("Failed to start code mode runner")

    proc.stdin.write(json.dumps(init_message) + "\n")
    proc.stdin.flush()

    audit: list[dict] = []
    console_output: list[str] = []
    result_payload = None
    error_payload = None
    runner_truncated = False
    request_seq = 0
    deadline = time.monotonic() + timeout_seconds

    while True:
        now = time.monotonic()
        if now > deadline:
            proc.kill()
            error_payload = TimeoutExecutionError(
                f"Execution exceeded timeout of {timeout_seconds} seconds"
            ).to_payload()
            break

        if proc.stdout.closed:
            break

        remaining = max(0, deadline - now)
        ready, _, _ = select.select([proc.stdout], [], [], min(0.2, remaining))

        if not ready:
            if proc.poll() is not None:
                break
            continue

        line = proc.stdout.readline()
        if line == "":
            if proc.poll() is not None:
                break
            continue

        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            continue

        msg_type = message.get("type")

        if msg_type == "result":
            result_payload = message.get("result")
            runner_console = message.get("console")
            if isinstance(runner_console, list):
                console_output = [str(v) for v in runner_console]
            runner_truncated = bool(message.get("truncated"))
            continue

        if msg_type == "error":
            error_payload = _normalize_runner_error(message.get("error"))
            runner_console = message.get("console")
            if isinstance(runner_console, list):
                console_output = [str(v) for v in runner_console]
            runner_truncated = bool(message.get("truncated"))
            continue

        if msg_type == "rpc_request":
            request_seq += 1
            request_id = message.get("id")
            request_payload = message.get("request", {})
            req_started = time.monotonic()
            audit_entry: dict = {"seq": request_seq}

            try:
                if mode != "execute":
                    raise PolicyError("RPC requests are only allowed in execute mode")
                if execute_fn is None:
                    raise RuntimeExecutionError("Execute function unavailable")

                check_call_cap(request_seq, max_requests)

                rpc_type = request_payload.get("type", "")

                if rpc_type == "rest_request" or adapter_type == "rest":
                    normalized = normalize_rest_request(
                        request_payload, allow_write=allow_write, assume_yes=assume_yes
                    )
                    audit_entry.update({
                        "method": normalized["method"],
                        "path": normalized["path"],
                    })
                    status_code, api_response = execute_fn(normalized)
                    audit_entry["status"] = status_code
                    audit_entry["duration_ms"] = int((time.monotonic() - req_started) * 1000)

                elif rpc_type == "mcp_call_tool" or adapter_type == "mcp":
                    normalized = normalize_mcp_request(
                        request_payload,
                        allow_write=allow_write,
                        assume_yes=assume_yes,
                        policy_config=policy_config or {},
                        allow_unknown_tools=allow_unknown_tools,
                    )
                    audit_entry["tool"] = normalized["tool"]
                    ok, api_response = execute_fn(normalized)
                    audit_entry["ok"] = bool(ok)
                    audit_entry["duration_ms"] = int((time.monotonic() - req_started) * 1000)

                else:
                    raise ValidationError(f"Unknown RPC type: {rpc_type}")

                audit.append(audit_entry)

                response_message = {
                    "type": "rpc_response",
                    "id": request_id,
                    "ok": True,
                    "result": api_response,
                }

            except CodemodeError as exc:
                audit_entry["duration_ms"] = int((time.monotonic() - req_started) * 1000)
                if "method" not in audit_entry and "tool" not in audit_entry:
                    if isinstance(request_payload, dict):
                        audit_entry["method"] = str(request_payload.get("method", "UNKNOWN")).upper()
                        audit_entry["path"] = request_payload.get("path")
                audit_entry.setdefault("status", None)
                audit.append(audit_entry)
                response_message = {
                    "type": "rpc_response",
                    "id": request_id,
                    "ok": False,
                    "error": exc.to_payload(),
                }

            except Exception as exc:
                audit_entry["duration_ms"] = int((time.monotonic() - req_started) * 1000)
                audit_entry.setdefault("status", None)
                audit.append(audit_entry)
                response_message = {
                    "type": "rpc_response",
                    "id": request_id,
                    "ok": False,
                    "error": RuntimeExecutionError(str(exc)).to_payload(),
                }

            if proc.stdin:
                proc.stdin.write(json.dumps(response_message) + "\n")
                proc.stdin.flush()

    try:
        proc.wait(timeout=1)
    except subprocess.TimeoutExpired:
        proc.kill()

    stderr_text = ""
    if proc.stderr is not None:
        stderr_text = proc.stderr.read().strip()

    if error_payload is None and proc.returncode not in (0, None) and result_payload is None:
        error_payload = RuntimeExecutionError(
            "Code mode runner exited with a non-zero status",
            {"returncode": proc.returncode, "stderr": stderr_text},
        ).to_payload()

    if error_payload is None and result_payload is None:
        error_payload = RuntimeExecutionError(
            "Code mode runner exited without returning a result",
            {"stderr": stderr_text},
        ).to_payload()

    total_duration_ms = int((time.monotonic() - started) * 1000)

    return build_envelope(
        success=error_payload is None,
        mode=mode,
        result=result_payload if error_payload is None else None,
        console=console_output,
        audit=audit,
        duration_ms=total_duration_ms,
        request_count=len(audit),
        max_requests=max_requests,
        timeout_seconds=timeout_seconds,
        truncated=runner_truncated,
        spec_sha256=spec_sha256,
        error=error_payload,
        result_max_bytes=result_max_bytes,
        console_max_bytes=console_max_bytes,
    )
