#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["requests"]
# ///
"""
Code Mode sidecar entry script for make-api.

Provides `codemode search` and `codemode execute` commands as a standalone script.
Does not modify the existing skill entry script.

Generated by codemode-scaffold. Template version: 1.0.0

Usage:
    codemode.py search --code 'async () => spec.operations.slice(0, 5)' [--json]
    codemode.py execute --code 'async () => await codemode.request(...)' [--allow-write] [--yes] [--json]
    codemode.py search --code-file search.js [--json]
    codemode.py execute --code-file run.js --allow-write --yes [--json]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Add scripts directory to path for template imports
SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))

from codemode_host import read_code_source, run_codemode
from codemode_output import format_envelope_human
from codemode_policy import ValidationError


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="codemode",
        description="Code Mode for make-api — sandboxed JavaScript execution",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # --- search ---
    search_parser = subparsers.add_parser("search", help="Search the API spec/tool index")
    search_parser.add_argument("--code", type=str, help="JavaScript code (inline)")
    search_parser.add_argument("--code-file", type=str, help="JavaScript code file")
    search_parser.add_argument("--timeout", type=int, default=30, help="Timeout in seconds")
    search_parser.add_argument("--refresh-spec", action="store_true", help="Force refresh of spec/index cache")
    search_parser.add_argument("--json", action="store_true", help="JSON output")

    # --- execute ---
    exec_parser = subparsers.add_parser("execute", help="Execute code against the API")
    exec_parser.add_argument("--code", type=str, help="JavaScript code (inline)")
    exec_parser.add_argument("--code-file", type=str, help="JavaScript code file")
    exec_parser.add_argument("--timeout", type=int, default=30, help="Timeout in seconds")
    exec_parser.add_argument("--max-requests", type=int, default=20, help="Max API requests")
    exec_parser.add_argument("--allow-write", action="store_true", help="Allow write operations")
    exec_parser.add_argument("--yes", action="store_true", help="Skip write confirmation")
    exec_parser.add_argument("--json", action="store_true", help="JSON output")

    return parser


def cmd_search(args: argparse.Namespace) -> int:
    """Handle `codemode search` command."""
    code = read_code_source(args.code, args.code_file)

    # Import adapter-specific index loader
    # {{ADAPTER_SEARCH_IMPORT}}
    spec_payload, spec_sha256 = load_search_index(refresh=args.refresh_spec)

    envelope = run_codemode(
        mode="search",
        code=code,
        adapter_type="mcp",
        adapter_name="codemode",
        timeout_seconds=args.timeout,
        max_requests=0,
        allow_write=False,
        assume_yes=False,
        spec_payload=spec_payload,
        spec_sha256=spec_sha256,
        scripts_dir=SCRIPTS_DIR,
    )

    if args.json:
        print(json.dumps(envelope, indent=2, ensure_ascii=False))
    else:
        print(format_envelope_human(envelope))

    return 0 if envelope["success"] else 1


def cmd_execute(args: argparse.Namespace) -> int:
    """Handle `codemode execute` command."""
    code = read_code_source(args.code, args.code_file)

    # Import adapter-specific executor
    # {{ADAPTER_EXECUTE_IMPORT}}
    adapter = create_adapter()

    # Load MCP policy config for tool classification
    config_path = SCRIPTS_DIR / "codemode-config.mcp.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    policy_config = config.get("policy", {})

    envelope = run_codemode(
        mode="execute",
        code=code,
        adapter_type="mcp",
        adapter_name="codemode",
        timeout_seconds=args.timeout,
        max_requests=args.max_requests,
        allow_write=args.allow_write,
        assume_yes=args.yes,
        execute_fn=adapter.execute,
        policy_config=policy_config,
        scripts_dir=SCRIPTS_DIR,
    )

    if args.json:
        print(json.dumps(envelope, indent=2, ensure_ascii=False))
    else:
        print(format_envelope_human(envelope))

    return 0 if envelope["success"] else 1


# --- Make API MCP adapter wiring ---

def load_search_index(refresh: bool = False) -> tuple[dict, str | None]:
    """Load Make API tool search index from MCP config."""
    import importlib.util as _iu

    index_script = SCRIPTS_DIR / "codemode-mcp-index.py"
    spec = _iu.spec_from_file_location("codemode_mcp_index", index_script)
    mod = _iu.module_from_spec(spec)
    spec.loader.exec_module(mod)

    # Load tool registry from config's read_tools + write_tools
    config_path = SCRIPTS_DIR / "codemode-config.mcp.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    policy = config.get("policy", {})

    all_tools = []
    for name in policy.get("read_tools", []):
        all_tools.append({"name": name, "description": f"Read tool: {name}"})
    for name in policy.get("write_tools", []):
        all_tools.append({"name": name, "description": f"Write tool: {name}"})

    index, _refreshed = mod.ensure_index(
        cache_dir=mod.default_cache_dir(),
        tools=all_tools,
        source="codemode-config.mcp.json",
        refresh=refresh,
        max_age_hours=mod.DEFAULT_MAX_AGE_HOURS,
    )

    spec_payload = {
        "operations": index.get("tools", []),
        "meta": {
            "schema_version": index.get("schema_version"),
            "generated_at": index.get("generated_at"),
            "tools_sha256": index.get("tools_sha256"),
        },
    }
    return spec_payload, index.get("tools_sha256")


def create_adapter():
    """Create the Make API MCP adapter."""
    import importlib.util as _iu

    adapter_script = SCRIPTS_DIR / "codemode-mcp-adapter.py"
    spec = _iu.spec_from_file_location("codemode_mcp_adapter", adapter_script)
    mod = _iu.module_from_spec(spec)
    spec.loader.exec_module(mod)

    # Load policy config for tool classification
    config_path = SCRIPTS_DIR / "codemode-config.mcp.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))

    return mod.McpAdapter()


def main():
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.command == "search":
            sys.exit(cmd_search(args))
        elif args.command == "execute":
            sys.exit(cmd_execute(args))
        else:
            parser.print_help()
            sys.exit(1)
    except ValidationError as exc:
        print(f"Error: {exc.message}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
