"""Code Mode MCP policy tests. Generated by codemode-scaffold."""
import sys
from pathlib import Path

import pytest

SCRIPTS_DIR = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

from codemode_policy import (
    PolicyError,
    ValidationError,
    classify_mcp_tool,
    normalize_mcp_request,
)


SAMPLE_POLICY = {
    "read_tools": ["scenarios_list", "scenarios_get"],
    "write_tools": ["scenarios_delete", "scenarios_create"],
    "pattern_rules": [
        {"type": "suffix", "pattern": "_list", "classification": "read"},
        {"type": "suffix", "pattern": "_delete", "classification": "write"},
    ],
}


def test_classify_explicit_read():
    assert classify_mcp_tool("scenarios_list", SAMPLE_POLICY) == "read"


def test_classify_explicit_write():
    assert classify_mcp_tool("scenarios_delete", SAMPLE_POLICY) == "write"


def test_classify_pattern_suffix_read():
    assert classify_mcp_tool("connections_list", SAMPLE_POLICY) == "read"


def test_classify_unknown():
    assert classify_mcp_tool("unknown_tool", SAMPLE_POLICY) == "unknown"


def test_write_tool_blocked_without_flags():
    with pytest.raises(PolicyError):
        normalize_mcp_request(
            {"tool": "scenarios_delete", "args": {"id": 1}},
            allow_write=False,
            assume_yes=False,
            policy_config=SAMPLE_POLICY,
        )


def test_unknown_tool_blocked_by_default():
    with pytest.raises(PolicyError):
        normalize_mcp_request(
            {"tool": "unknown_tool", "args": {}},
            allow_write=False,
            assume_yes=False,
            policy_config=SAMPLE_POLICY,
            allow_unknown_tools=False,
        )


def test_read_tool_allowed():
    result = normalize_mcp_request(
        {"tool": "scenarios_list", "args": {"teamId": 1}},
        allow_write=False,
        assume_yes=False,
        policy_config=SAMPLE_POLICY,
    )
    assert result["tool"] == "scenarios_list"
    assert result["classification"] == "read"
