"""Code Mode MCP integration tests. Generated by codemode-scaffold."""
import shutil
import sys
from pathlib import Path

import pytest

SCRIPTS_DIR = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

from codemode_host import run_codemode


SAMPLE_POLICY = {
    "read_tools": ["test_list"],
    "write_tools": ["test_create"],
    "pattern_rules": [],
}


@pytest.mark.skipif(shutil.which("node") is None, reason="node required")
def test_search_with_tool_index():
    envelope = run_codemode(
        mode="search",
        code="async () => spec.operations.length",
        adapter_type="mcp",
        timeout_seconds=5,
        max_requests=0,
        spec_payload={"operations": [
            {"name": "test_list", "description": "List tests"},
        ]},
        spec_sha256="test-sha",
        scripts_dir=SCRIPTS_DIR,
    )
    assert envelope["success"] is True
    assert envelope["result"] == 1


@pytest.mark.skipif(shutil.which("node") is None, reason="node required")
def test_execute_read_tool():
    def fake_execute(req):
        return True, {"items": [{"id": 1}]}

    envelope = run_codemode(
        mode="execute",
        code="async () => await codemode.callTool({ tool: 'test_list', args: {} })",
        adapter_type="mcp",
        adapter_name="codemode",
        timeout_seconds=5,
        max_requests=5,
        execute_fn=fake_execute,
        policy_config=SAMPLE_POLICY,
        scripts_dir=SCRIPTS_DIR,
    )
    assert envelope["success"] is True
    assert len(envelope["audit"]) == 1
